name: Hub Point Media
favicon: null
layout_spectrum: 0.7384528906550258
typography_spectrum: 0.32701944513246417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21344578033313155
  lightness: 0.4121225355193019
  saturation: 0.3907551127485931
  rhythmicContrast: 0.28306127595715225
purpose: []
