name: Hub Point Media
favicon: null
layout_spectrum: 0.17417
typography_spectrum: 0.32701944513246417
title: Something here....
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9ecfb'
    - '#010511'
    - '#596e81'
    - '#c2b3a0'
    - '#a35c56'
  brandStrength: 0.5625
  lightness: 0.4121225355193019
  saturation: 0.3907551127485931
  rhythmicContrast: 0.28306127595715225
purpose: []
